#!/bin/bash

WF_SSID=WirelessSSID
WF_PASSPHRASE=password
WF_SCRIPTS=Y

read -p "SSID [$WF_SSID]: " -e t1
if [ -n "$t1" ]; then WF_SSID="$t1";fi

read -p "Password [$WF_PASSPHRASE]: " -e t1
if [ -n "$t1" ]; then WF_PASSPHRASE="$t1";fi

read -p "Create script events? [$WF_SCRIPTS]: " -e t1
if [ -n "$t1" ]; then WF_SCRIPTS="$t1";fi


cat <<EOF > /etc/network/interfaces

#created by $0
#
# Network interfaces autogenerated file
#

auto lo

iface lo inet loopback
iface eth0 inet dhcp
	pre-up /usr/local/bin/upWifi.sh

auto wlan0
allow-hotplug wlan0
iface wlan0 inet dhcp
  wpa-ssid "$WF_SSID"
  wpa-psk  "$WF_PASSPHRASE"
  post-down /etc/network/if-up.d/upWifi.sh
  pre-up /etc/network/if-down.d/upWifi.sh
EOF
  rc=$?
  if [[ $rc != 0 ]] ; then
    echo -en "[FAIL]\n"
    echo ""
    exit $rc
  else
    echo -en "[OK]\n"
  fi
#  echo -en "[OK]\n"


if [ "$WF_SCRIPTS" == "Y" ]
then

cat <<EOF > /etc/network/if-up.d/upWifi.sh
#!/bin/bash
#created by $0
#
# Run script if network goes down
#
echo "`date -u` network DOWN" >> /home/pi/ntwlog.txt

EOF
  rc=$?
  if [[ $rc != 0 ]] ; then
    echo -en "[FAIL]\n"
    echo ""
    exit $rc
  else
    echo -en "[OK]\n"
  fi
#  echo -en "[OK]\n"


cat <<EOF > /etc/network/if-down.d/upWifi.sh
#!/bin/bash
#created by $0
#
# Run script if network goes up
#

echo "`date -u` network UP" >> /home/pi/ntwlog.txt


EOF
  rc=$?
  if [[ $rc != 0 ]] ; then
    echo -en "[FAIL]\n"
    echo ""
    exit $rc
  else
    echo -en "[OK]\n"
  fi
#  echo -en "[OK]\n"


fi

sudo chmod 755 /etc/network/if-up.d/upWifi.sh
sudo chmod 755 /etc/network/if-down.d/upWifi.sh



